services:
  - type: web
    name: cv usermanagement api
    runtime: node
    repo: https://github.com/chikatetsu/code-valley-user-management
    region: frankfurt # optional (defaults to oregon)
    buildCommand: npm install
    startCommand: npm start
    plan: free # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    envVars:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD:
      PGHOST: 176.134.7.134
      PGPORT: 5432
      APP_PORT: 3000
      APP_HOSTNAME: https://user-management.code-valley.xyz
      DYNO_CODE_URL: http://dyno-code.code-valley.xyz
      JWT_SECRET: 
      JWT_EXPIRES: 1d
      GOOGLE_CLIENT_ID: 456906997933-lt62fb1rjn1t25k3p7otjf06tu0ttb8j.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET:
      FIREBASE_STORAGE_BUCKET: pa2024-free.appspot.com
      FIREBASE_PRIVATE_KEY_BASE64:
      FRONTEND_URL: https://front.code-valley.xyz
